package com.rpgenerator.core.api

import kotlinx.serialization.Serializable

/**
 * Events emitted by the game engine.
 * These represent all changes to the game state and narrative.
 */
@Serializable
sealed class GameEvent {
    /**
     * Narrator describing the scene or action results.
     */
    @Serializable
    data class NarratorText(val text: String) : GameEvent()

    /**
     * NPC speaking to the player.
     */
    @Serializable
    data class NPCDialogue(
        val npcId: String,
        val npcName: String,
        val text: String
    ) : GameEvent()

    /**
     * System notification (level up, quest complete, achievement, etc.)
     */
    @Serializable
    data class SystemNotification(val text: String) : GameEvent()

    /**
     * Combat or action log entry.
     */
    @Serializable
    data class CombatLog(val text: String) : GameEvent()

    /**
     * Player stat change.
     */
    @Serializable
    data class StatChange(
        val statName: String,
        val oldValue: Int,
        val newValue: Int
    ) : GameEvent()

    /**
     * Item added to inventory.
     */
    @Serializable
    data class ItemGained(
        val itemId: String,
        val itemName: String,
        val quantity: Int = 1
    ) : GameEvent()

    /**
     * Quest update (new, completed, failed).
     */
    @Serializable
    data class QuestUpdate(
        val questId: String,
        val questName: String,
        val status: QuestStatus
    ) : GameEvent()

    // ── Multimodal Events (Gemini interleaved output) ──────────────

    /**
     * Scene art generated by Gemini, displayed as full-screen background.
     */
    @Serializable
    data class SceneImage(
        val imageData: ByteArray,
        val description: String
    ) : GameEvent()

    /**
     * Narrator voice audio chunk for playback.
     */
    @Serializable
    data class NarratorAudio(
        val audioData: ByteArray,
        val sampleRate: Int = 24000
    ) : GameEvent()

    /**
     * Background music mood shift.
     */
    @Serializable
    data class MusicChange(
        val mood: String,
        val audioData: ByteArray? = null
    ) : GameEvent()

    /**
     * NPC portrait generated when player meets an NPC.
     */
    @Serializable
    data class NPCPortrait(
        val npcId: String,
        val npcName: String,
        val imageData: ByteArray
    ) : GameEvent()

    /**
     * Item icon generated (async, arrives after item is added).
     */
    @Serializable
    data class ItemIconGenerated(
        val itemId: String,
        val iconUrl: String
    ) : GameEvent()

    /**
     * Raw tool call results from the GM's turn.
     * Always emitted so clients have structured data (class options, character sheet, etc.)
     * independent of whether narration happened.
     */
    @Serializable
    data class ToolCallResults(
        val results: List<ToolResultEntry>
    ) : GameEvent()
}

@Serializable
data class ToolResultEntry(
    val toolName: String,
    val success: Boolean,
    val data: String  // JSON string of the tool's result data
)

@Serializable
enum class QuestStatus {
    NEW,
    IN_PROGRESS,
    COMPLETED,
    FAILED
}
